config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :tasks do #, only: [:index, :show, :new, :create, :edit]
      resources :work_periods
    end
  end
  root "users#index"
  #get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :work_periods, dependent: :destroy

  validates :description, presence: true
  validates :estimated_duration, presence: true

  enum priority: [ :low, :medium, :high ]
  validates :priority, presence: true

  #validates :score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100, message: "score is not within the valid range [0,100]"}
end

app/controllers/tasks_controller.rb
require 'date'

class TasksController < ApplicationController
  before_action :set_user

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.where(user_id: @user.id, active: true)
  end

  # GET /tasks/new
  def new
    @task = @user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    duration_in_seconds = task_params["estimated_duration(4i)"].to_i * 3600 + task_params["estimated_duration(4i)"].to_i * 60
    due_date = DateTime.new(task_params["due_date(1i)"].to_i, 
                        task_params["due_date(2i)"].to_i, 
                        task_params["due_date(3i)"].to_i, 
                        task_params["due_date(4i)"].to_i, 
                        task_params["due_date(5i)"].to_i)
    @task = Task.new(description: task_params["description"], 
                     active: true,
                     priority: task_params["priority"],
                     estimated_duration: duration_in_seconds,
                     due_date: due_date,
                     user_id: @user.id 
                    )

    respond_to do |format|
      if @task.save
        format.html { redirect_to @user, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        flash.now[:error] = @task.errors.full_messages + :user_id
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def complete 
    @task.active = false
    if @task.update(task_params)
      format.html { redirect_to @task, notice: 'Task was successfully updated.' }
      format.json { render :show, status: :ok, location: @task }
    else
      format.html { render :task }
      format.json { render json: @task.errors, status: :unprocessable_entity }
      end


  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :estimated_duration, :priority, :user_id, :due_date)
    end

    def seconds_to_time(s)
      if (s)
        Time.new(0, 1, 1, (s / 3600).floor, (s % 3600) / 60)    #TODO: make pretty
      end
    end

    def time_to_seconds(t)
      if (t)
        t.hour * 3600 + t.min * 60
      end
    end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for([user, task]) do |form| %>
  <%= form.input :description %>
  <%= form.input :estimated_duration, as: :time%>
  <%= form.input :due_date, as: :datetime, placeholder: DateTime.now %>
  <% if false %>
    <%= select_datetime DateTime.now, prefix: :due_date%>
  <% end %>
  <%= form.input :priority, collection: Task.priorities.keys, selected: Task.priorities.keys[1] %> 
  <%= form.button :submit, class: "btn-primary" %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Active</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.estimated_duration %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', user_tasks_url %></td>


        <% if false %>
        <td><%= link_to 'Edit', edit_user_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if false %>
<%= link_to 'New Task', new_task_path %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', user: @user, task: @task %>

<%= link_to 'Back', user_tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @task.active %>
</p>

<p>
  <strong>Score:</strong>
  <%= @task.score %>
</p>

<%= link_to 'Edit', edit_user_task_path(@task) %> |
<%= link_to 'Back', user_tasks_path %>