config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :tasks do #, only: [:index, :show, :new, :create, :edit]
      resources :work_periods
    end
  end
  root "users#index"
  #get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :work_periods, through: :tasks
  validates :first_name, presence: true
  validates :daily_hours, numericality: {only_integer: true, greater_than: 0, less_than: 24, message: "Available daily work hours need to be greater than 0 and less than or equal to 24" }
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
    format: { with: VALID_EMAIL_REGEX }

  enum rank: [ :bronze, :silver, :gold, :platinum, :diamond ]

  def active_tasks
    tasks.where("active = ? ", true);
    #tasks.where("user_id = ? AND active = ?", params[:id, true]).order(:priority, :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, flash: { success: 'User was successfully created.' }}
        format.json { render :show, status: :created, location: @user }
      else
        flash.now[:error] = user.errors.full_messages
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :email, :password, :password_confirmation, :daily_hours)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(user) do |form| %>

  <%= form.input :first_name %>
  <%= form.input :email %>
  <%= form.input :password %>
  <%= form.input :password_confirmation %>
  <%= form.input :daily_hours %>
  <%= form.button :submit, class: "btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Users</h1>
  <ul class="actions">
    <li>
      <%= link_to "New User", new_user_path, class: "new" %>
    </li>
  </ul>
</div>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Email</th>
      <th>Daily hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.first_name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.daily_hours %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.first_name %></h1>
  <ul class="actions">
    <li><%= link_to " New Task", new_user_task_url(@user), class: "new"%></li>
    <li><%= link_to " Edit", edit_user_path(@user), class: "edit"%></li>
    <li><%= link_to " Delete", 
      user_path(@user), 
      method: :delete, 
      data: { confirm: "Are you sure you want to delete this user?" },
      class: "delete"%>
    </li>
  </ul>
</div>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
  <br/>
  <strong>Estimated Work remaining:</strong>
  <%= @user.daily_hours %>
  <br/>


  <h3>Tasks</h3>
  </br>
  <% @user.tasks.each do |task|%>
    <div class='task-item'>
      <strong><%= task.description %></strong>
      (Minutes left: <%=(task.estimated_duration / 60).floor %>)
      <a href="" class='start btn btn-primary'>Complete</a>
      <a href="" class='start btn btn-primary'>Start</a>
    </div>
  <% end %>
</p>