config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :tasks do #, only: [:index, :show, :new, :create, :edit]
      resources :work_periods
    end
  end
  root "users#index"
  #get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work_period.rb
class WorkPeriod < ApplicationRecord
  belongs_to :task
  validates :duration, presence: true, numericality: {integer: true, greater_than: 0}

end

app/controllers/work_periods_controller.rb
class WorkPeriodsController < ApplicationController
  before_action :set_work_period, only: [:show, :edit, :update, :destroy]

  # GET /work_periods
  # GET /work_periods.json
  def index
    @work_periods = WorkPeriod.all
  end

  # GET /work_periods/1
  # GET /work_periods/1.json
  def show
  end

  # GET /work_periods/new
  def new
    @work_period = WorkPeriod.new
  end

  # GET /work_periods/1/edit
  def edit
  end

  # POST /work_periods
  # POST /work_periods.json
  def create
    @work_period = WorkPeriod.new(work_period_params)

    respond_to do |format|
      if @work_period.save
        format.html { redirect_to @work_period, notice: 'Work period was successfully created.' }
        format.json { render :show, status: :created, location: @work_period }
      else
        format.html { render :new }
        format.json { render json: @work_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_periods/1
  # PATCH/PUT /work_periods/1.json
  def update
    respond_to do |format|
      if @work_period.update(work_period_params)
        format.html { redirect_to @work_period, notice: 'Work period was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_period }
      else
        format.html { render :edit }
        format.json { render json: @work_period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_periods/1
  # DELETE /work_periods/1.json
  def destroy
    @work_period.destroy
    respond_to do |format|
      format.html { redirect_to work_periods_url, notice: 'Work period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_period
      @work_period = WorkPeriod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_period_params
      params.fetch(:work_period, {})
    end
end

app/helpers/work_periods_helper.rb
module WorkPeriodsHelper
end

app/views/work_periods/_form.html.erb
<%= form_with(model: work_period, local: true) do |form| %>
  <% if work_period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_period.errors.count, "error") %> prohibited this work_period from being saved:</h2>

      <ul>
      <% work_period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/work_periods/edit.html.erb
<h1>Editing Work Period</h1>

<%= render 'form', work_period: @work_period %>

<%= link_to 'Show', @work_period %> |
<%= link_to 'Back', work_periods_path %>

app/views/work_periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Periods</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_periods.each do |work_period| %>
      <tr>
        <td><%= link_to 'Show', work_period %></td>
        <td><%= link_to 'Edit', edit_work_period_path(work_period) %></td>
        <td><%= link_to 'Destroy', work_period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Period', new_work_period_path %>

app/views/work_periods/new.html.erb
<h1>New Work Period</h1>

<%= render 'form', work_period: @work_period %>

<%= link_to 'Back', work_periods_path %>

app/views/work_periods/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_work_period_path(@work_period) %> |
<%= link_to 'Back', work_periods_path %>